-- apply_videos seed — exact 22 rows from nudgeable production database.
-- Run AFTER migration 20240617_apply_videos.sql.

TRUNCATE public.apply_videos;

INSERT INTO public.apply_videos
  (id, title, description, video_url, thumbnail_url, duration, order_index, is_published, is_locked, group_name, category_tag, platforms)
VALUES

('97a48e5c-0e5e-44f4-b40b-99eae2c78018',
 'Canvas - Edit AI responses like a live document',
 E'Edit AI replies inline - surgically\n\nInstead of asking AI to rewrite the whole response, Canvas opens it as a live document. Highlight one paragraph, give a new instruction, and only that part changes. Perfect for drafts, reports, and code where you want precision edits - not a full regeneration.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778227393752-y0qs2m8nfks.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778340838477-r39ibmqiui.jpeg',
 '0:18', 0, true, false, 'Features', 'EDITING', 'ChatGPT | Claude | Gemini'),

('a3ae9da4-9554-495a-b989-28468b50545d',
 'Notebook - AI answers only from your documents',
 E'AI answers grounded in your sources, not the internet\n\nUpload your own documents, PDFs, or notes and the AI answers exclusively from that material - not from the web or its training data. Ideal for analysing a report, studying a policy document, or researching a topic using only trusted sources you provide.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778229095845-ex29cgizgd.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778340890577-ocqxmbppyr.jpeg',
 '0:30', 1, true, false, 'Features', 'KNOWLEDGE', 'Gemini | Copilot'),

('356b69d6-7579-4a02-8974-85fb3e5d6e09',
 'Projects - One workspace that remembers your context',
 E'One persistent workspace for ongoing work\n\nGroup related chats and files under a project. The AI remembers your context across every session - your role, your goal, your previous decisions. No re-explaining every time you open a new chat.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778230827720-064nkbnnlfua.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341709222-hzzq3v4tyua.jpeg',
 '0:28', 2, true, false, 'Features', 'PRODUCTIVITY', 'Copilot | ChatGPT | Claude'),

('7f216251-3d6d-4815-be86-a44cf20e5a7f',
 'Connect Apps - AI reads your real work data',
 E'Let AI read your actual work data\n\nConnect Gmail, Drive, Calendar, or other tools so the AI can pull real information from your actual accounts - not just answer from memory. Ask it to summarise today''s emails, find a file, or check your schedule.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778236518335-blsm09ciso6.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341153747-m10q4ezsaj.jpeg',
 '0:15', 3, true, false, 'Features', 'PRODUCTIVITY', 'Gemini | Copilot | ChatGPT | Claude'),

('7567b54c-73ee-4521-baaa-564779424367',
 'Custom Instructions - Set your rules once, forever',
 E'Stop repeating yourself in every chat\n\nSet permanent rules once - your role, your preferred tone, what to avoid, how long answers should be - and the AI follows them automatically in every conversation without you having to re-explain.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778236919649-0goq4pd72m9l.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341180517-1c6hpczz6p1.jpeg',
 '0:11', 4, true, false, 'Features', 'PERSONAL', 'Gemini | Copilot | ChatGPT | Claude'),

('b100cb52-8ba7-42dc-af62-d3820f4a489e',
 'Memories - AI remembers you across every chat',
 E'AI that learns who you are over time\n\nThe AI remembers facts about you across conversations - your job title, preferences, recurring context - and uses them to give sharper, more relevant answers without you repeating background every session.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1777880978012-b6xqyrek008.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341636599-2uxt9zpt4hl.jpeg',
 '0:16', 5, true, false, 'Features', 'PERSONAL', 'Gemini | Copilot | ChatGPT | Claude'),

('937d6894-ba02-46dc-a711-b7f9b1f5405e',
 'Temporary Chats - Chat with AI, leave no trace',
 E'Go incognito with AI\n\nNothing is saved, nothing is memorised, nothing is used for training. Temporary chats are for sensitive queries or one-off tasks you don''t want stored anywhere.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778242041014-g18t2maadi.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341689317-9wctgcngoh9.jpeg',
 '0:10', 6, true, false, 'Features', 'PERSONAL', 'Gemini | Copilot | ChatGPT | Claude'),

('5219511c-ecd3-4008-89c6-f56b07cfa4ac',
 'Thinking Models - How long AI should reason before responding',
 E'AI that reasons before it answers\n\nInstead of responding instantly, the model works through the problem step by step before giving an answer. Better accuracy on complex analysis, multi-step logic, and tricky decisions where a quick answer would likely be wrong.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778242223080-16zqx1qkov4.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341059099-axyoqr8xfe6.jpeg',
 '0:12', 7, true, false, 'Features', 'PRODUCTIVITY', 'Gemini | Copilot | ChatGPT | Claude'),

('3bd64d41-0be3-44ec-a475-3106c71f7871',
 'Design Images - Turn a text prompt into a visual',
 E'Generate visuals from a text prompt\n\nDescribe what you want - a product mockup, a social media graphic, an illustration - and the AI creates it. No design tools, no designer needed.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778242763342-trprpilu7a.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341657059-auazufp3nvb.jpeg',
 '0:18', 8, true, false, 'Workflows', 'CREATIVE', 'Gemini | Copilot | ChatGPT'),

('8ab7f6ca-a6f2-4925-96bf-fabc2780906a',
 'Deep Research - AI searches multiple sources and delivers a structured report',
 E'AI that researches like an analyst, not a search engine\n\nGive it a topic and it autonomously searches dozens of sources, reads them, cross-references findings, and delivers a structured report. What takes a human analyst hours takes minutes.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778258728267-nx1poywx9vr.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341516567-v59t7c7t1d.jpeg',
 '0:36', 9, true, false, 'Features', 'KNOWLEDGE', 'Gemini | Copilot | ChatGPT | Claude'),

('7e9e6580-70e0-4cd3-b96b-eb76d27b8265',
 'Scheduled Actions - AI runs tasks even when you''re not there',
 E'AI that works even when you''re not there\n\nSet a task to run at a specific time or on a recurring schedule - daily briefings, weekly summaries, automated prompts. You define it once, AI executes it without you being in the chat.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778258960657-kkjq85zgq3.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341671115-mawbmzwqk8n.jpeg',
 '0:18', 10, true, false, 'Features', 'PRODUCTIVITY', 'Gemini | Copilot | ChatGPT'),

('bb571603-5b87-4cb4-b081-5f082091003b',
 'Design Videos - Turn a text prompt into a short video',
 E'Turn a text prompt into a short video\n\nDescribe a scene, concept, or message and the AI generates a short video clip. No camera, no editor, no production team needed.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778259129040-qs05voosoe.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341081578-penejqg8kfh.jpeg',
 '0:14', 11, true, false, 'Workflows', 'CREATIVE', 'Gemini'),

('6fbc0052-236d-4150-bd5c-16dd27941874',
 'AI in Excel - AI writes formulas and builds charts inside your spreadsheet',
 E'Your data analyst, sitting inside your spreadsheet\n\nAI works directly inside the file - writes formulas, cleans messy data, builds charts, and answers questions about your numbers in plain language. No switching between tools.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778259518155-qvpttni8mjo.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341531408-ddz60by0yaj.jpeg',
 '0:23', 12, true, false, 'Workflows', 'ANALYTICS', 'Gemini | Copilot'),

('3152ed02-b6e8-4ebc-acdc-06baa00b584f',
 'Gems (Custom Chatbots) - Build a saved AI assistant with a fixed role and instructions',
 E'Build a bot so you never type the same prompt again\n\nInstead of starting every chat with a long system prompt, build a saved AI assistant with a fixed role, tone, and instructions. Open it, type your question, get a consistent response - every time.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778260099621-u2tl4k8z1b.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341469420-wkvawideaj.jpeg',
 '0:37', 13, true, false, 'Features', 'PERSONAL', 'Gemini | Copilot | ChatGPT | Claude'),

('d9605b66-ac30-4633-a526-2c071ce908f3',
 'Guided Learning & Quizzes - AI teaches you a topic and tests your understanding',
 E'AI as your on-demand tutor\n\nAsk the AI to teach you a topic, then quiz you on it. It explains, tests your understanding, and corrects mistakes in real time - structured learning without a course or a trainer.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778260299274-m2rgmvhncwq.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341555896-tzw6snu54uk.jpeg',
 '0:28', 14, true, false, 'Features', 'KNOWLEDGE', 'Gemini | Copilot | ChatGPT | Claude'),

('bd0e272a-dd0c-47ba-904c-699283274d9d',
 'Design Infographics - Turn data or concepts into a shareable visual',
 E'Turn data or concepts into shareable visuals\n\nDescribe what you want to communicate and the AI designs an infographic - comparisons, timelines, stats, frameworks - structured and visual, ready to drop into a deck or post.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778260556006-0wuhkcjsk2m.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341619564-5hy487yquno.jpeg',
 '0:13', 15, true, false, 'Workflows', 'CREATIVE', 'Gemini | Copilot | ChatGPT | Claude'),

('e43c10c1-d6ba-47b6-8f1f-57706fde7150',
 'Design Dashboards - AI builds charts, KPIs, and tables without coding',
 E'Build a live data view without a developer\n\nDescribe your metrics and the AI assembles a dashboard with charts, KPIs, and tables. No coding, no BI tool license needed.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778260805845-c9f916vfwtm.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341425449-mvyp5m6f8q.jpeg',
 '0:20', 16, true, false, 'Workflows', 'ANALYTICS', 'Gemini | Copilot | ChatGPT | Claude'),

('506c9e61-50f6-43e3-a262-bce6ad093dcc',
 'AI Browsers - AI browses, fills forms, and completes tasks across websites',
 E'A browser that takes actions, not just searches\n\nAI-native browsers (Comet by Perplexity, Atlas by OpenAI) don''t just retrieve information - they browse on your behalf, fill forms, complete multi-step tasks, and take real actions across websites. The next step beyond chatbots.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778261413449-ve3u724ct9.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341136868-ysb4chpgqba.jpeg',
 '0:33', 17, true, true, 'Apps', 'EXPLORATION', 'Comet (Perplexity) | Operator/Atlas (OpenAI)'),

('6ac1c1af-8443-4f50-ac6e-7255aa7450c0',
 'Design Slides (PPT) - AI builds a structured presentation from a topic',
 E'From a topic to a full deck in minutes\n\nDescribe your subject and the AI builds a structured, designed presentation - slides, layout, content. Edit what you need or regenerate sections with a single prompt.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778261862640-54agt7dqikb.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341595423-3a9fzry0w2r.jpeg',
 '0:26', 18, true, true, 'Workflows', 'PRODUCTIVITY', 'Gemini | Copilot | ChatGPT | Claude'),

('87cec619-4c2f-4be3-8320-482daecde099',
 'Data Analytics - Ask questions about your data and get answers in plain English',
 E'Ask questions about your data in plain English\n\nUpload a dataset and the AI analyses it - finds trends, flags anomalies, calculates metrics, and explains findings in plain language. No formulas, no SQL, no pivot tables.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778262054499-2qc0xdaukd.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341491992-t4hvisry2wl.jpeg',
 '0:20', 19, true, true, 'Workflows', 'ANALYTICS', 'Gemini | Copilot | ChatGPT | Claude'),

('5edec3c3-0bf1-410a-a970-48fc300059c0',
 'Create Agents & Automation - AI completes multi-step tasks end to end without you',
 E'Build AI that completes multi-step tasks without you\n\nDesign agents that take autonomous actions - browse the web, send emails, update records, trigger workflows - end to end. You define the goal, the agent figures out the steps.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778262794479-8qvowf08ew4.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341116744-ndemcwdiuol.jpeg',
 '1:10', 20, true, true, 'Skills', 'AUTOMATION', 'Google AI Studio | Copilot Studio'),

('32641e06-8d12-4f7b-a95a-0aab3747d15c',
 'Vibe Coding - Describe what you want to build and AI writes, runs, and refines the code',
 E'Build working software by describing it in plain English\n\nNo IDE, no syntax, no prior coding knowledge needed. Describe what you want to build, and the AI writes, runs, tests, and refines the code through conversation. From idea to working app in hours.',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-videos/1778262693660-s8klroyjh0c.mp4',
 'https://elxhnogqrfidlqwzbhlx.supabase.co/storage/v1/object/public/content/apply-thumbs/1778341789818-5lzcnn0cohu.jpeg',
 '0:52', 21, true, true, 'Skills', 'CREATIVE', 'Codex (OpenAI) | Claude Code | Google AI Studio');
